version: '3'

services:
  vlmcsd:
    image: yourusername/vlmcsd:latest
    container_name: vlmcsd
    restart: unless-stopped
    ports:
      - "1688:1688"  # KMS 服务端口
      - "80:80"      # Web 界面端口
    volumes:
      - ./config:/etc/vlmcsd
    healthcheck:
      test: ["CMD", "vlmcs", "127.0.0.1"]
      interval: 60s
      timeout: 3s
      retries: 3 